Changed install script to make it compatible for sh on linux
microsoft/artifacts-credprovider pull request #457
Opened 2023-10-25 00:51 UTC by amp-powell

2023-10-25 16:40 UTC, JohnSchmeichel commented
Works with default options, but if I set AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION then I get errors:

```sh
export AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION=v1.1.0-alpha
sh -c "$(curl -fsSL https://raw.githubusercontent.com/microsoft/artifacts-credprovider/ba93b5218249ec3792470f9b2f48c91bd930a016/helpers/installcredprovider.sh)"
```

still gives me an error `sh: 19: [: v1.1.0-alpha: unexpected operator`

2023-10-25 17:02 UTC, JohnSchmeichel requested changes

2023-10-25 17:12 UTC, JohnSchmeichel commented on helpers/installcredprovider.sh
> +  if [ ! -z ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} ] && [ ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} == 0.* ] || [ "$AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION" = "v0.*" ]; then
Think we can convert this to a case statement instead, which should work for both and simplify things:

```sh
  case ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} in
    0.*|v0.*)
        echo "ERROR: To install NET6 cred provider using the USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER variable, version to be installed must be 1.0.0. or greater. Check your AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION variable."
        exit 1
        ;;
  esac
```

2023-10-25 18:22 UTC, phil-hodgson commented
If we're making this work for environments without bash, should we also update the file's [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))?

2023-10-25 18:35 UTC, phil-hodgson commented
The issue customers faced is that on some environments, the customer had to first install bash before they could get the cred provider installed. The installation script should work whether bash is available or not.

2023-10-25 20:26 UTC, amp-powell commented on helpers/installcredprovider.sh
> +  if [ ! -z ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} ] && [ ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} == 0.* ] || [ "$AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION" = "v0.*" ]; then
Made these changes!

2023-10-25 22:15 UTC, JohnSchmeichel commented on helpers/installcredprovider.sh
> +  if [ ! -z ${AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION} ]; then
you should be able to remove this entirely, as if it's null it will just drop through the case

2023-10-26 19:04 UTC, JohnSchmeichel approved these changes

2023-10-26 19:56 UTC, merged